name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.8

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install Pylint
        run: pip install pylint

      - name: Run Pylint
        run: pylint .

      - name: Generate Build Artifact
        run: |
          mkdir build_output
          # Copying specific Python scripts from the src directory
          cp src/basic_GUI.py build_output/
          cp src/main.py build_output/
          cp src/tracker.py build_output/
          cp src/uploader.py build_output/

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact-${{ github.run_id }}
          path: build_output/

      - name: Display Logs
        run: echo "Build and lint checks completed"
