name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.8

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install Pylint and diffoscope
        run: pip install pylint diffoscope

      - name: Run Pylint
        run: pylint .

      - name: Generate Build Artifact
        run: |
          # Add your build commands here
          # For example: python setup.py build
          # Store the output in a directory, e.g., 'build_output/'
          mkdir build_output
          echo "Build files go here" > build_output/build.txt

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: build_output/

      - name: Display Logs
        run: echo "Build and lint checks completed" 
