name: CI

on:
  push:
    branches: [ "main", "versioncntrl-integration" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.12

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install Pylint
        run: pip install pylint

      - name: Run Pylint
        run: pylint . > pylint_log.txt

      - name: Generate Build Artifact
        run: |
          mkdir build_output
          cp src/main.py build_output/
          cp src/tracker2.py build_output/
          cp src/process_video.py build_output/
          cp src/movement_recognizer.py build_output/
          cp pylint_log.txt build_output/

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact-${{ github.run_id }}
          path: build_output/

      - name: Upload Pylint Log
        uses: actions/upload-artifact@v2
        with:
          name: pylint-log-${{ github.run_id }}
          path: pylint_log.txt

      - name: Display Logs
        run: cat pylint_log.txt
